model:
  name: resnet2d
  args:
    model_depth: 18
    pretrained: true

optimizer:
  name: SGD
  epochs: 25
  model_sp:
    args:
      lr: 0.01
      momentum: 0.9
      weight_decay: 1.0e-4
  
  schedule:
    name: StepLR
    args:
      step_size: 10
      gamma: 0.1
  
criterion:
  name: KDLoss
  args: {}