model:
  name: resnet2d
  args:
    model_depth: 18
    pretrained: true

adversary:
  name: PGD
  args:
    eps: 0.03
    alpha: 0.008
    iters: 7
    scale: [0.229, 0.224, 0.225]
    dim: 2

optimizer:
  name: SGD
  epochs: 25
  model_sp:
    args:
      lr: 0.01
      momentum: 0.9
      weight_decay: 1.0e-4
  model:
    args:
      lr: 0.01
  
  schedule:
    name: StepLR
    args:
      step_size: 10
      gamma: 0.1
  
criterion:
  name: KDLoss
  args: {}