dataset:
  name: hmdb
  batch_size: 128

  transform:
    resize: 128
    crop: 112
    hflip: true
    color_jitter: [0.4, 0.4, 0.4, 0.4]
    normalize: 
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  args:
    train:
      n_clips: 1
      n_frames: 16
      fps: 16
    test:
      n_clips: 1
      n_frames: 16
      fps: 16
    test_final:
      n_clips: 10
      n_frames: 16
      fps: 16

model:
  name: resnet2d
  ddp: true
  freeze_bn: true
  args:
    n_class: 51
    model_depth: 18
    dropout: 0.5
    pretrained: true

optimizer:
  name: SGD
  epochs: 30
  args:
    lr: 0.001
    momentum: 0.9
    weight_decay: 1.0e-3
  
  schedule:
    name: StepLR
    args:
      step_size: 20
      gamma: 0.1

criterion:
  name: CrossEntropyLoss
  args: {}
  
