dataset:
  name: hmdb
  batch_size: 32

  transform:
    resize: 256
    crop: 224
    hflip: true
    color_jitter: [0.4, 0.4, 0.4, 0.4]
    normalize: 
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  args:
    train:
      n_clips: 1
      n_frames: 8
      fps: 8
    test:
      n_clips: 1
      n_frames: 8
      fps: 8
    test_final:
      n_clips: 10
      n_frames: 8
      fps: 8

model:
  name: tsm
  args:
    n_class: 51
    arch: resnet18
    pretrained: true
    num_segments: 8
    shift_div: 8
    dropout: 0.5

optimizer:
  name: SGD
  epochs: 30
  args:
    lr: 0.001
    momentum: 0.9
    weight_decay: 1.0e-3
  
  schedule:
    name: StepLR
    args:
      step_size: 20
      gamma: 0.1

criterion:
  name: CrossEntropyLoss
  args: {}
  
